services:
  telegram-bot:
    build: .
    container_name: telegram-group-manager
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s

networks:
  bot-network:
    driver: bridge